### PR TITLE
Remove .idea/encodings.xml from version control and update .gitignore.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
I have updated the configuration for Inspections-4. Post that, the build seems to have succeeded. If this works, I will fix the configuration for all the other inspection builds. 
The real test will be, if you can do a commit with inspection violations for each of the profiles, let us see if they get detected?

**Comment by nikhilnanivadekar** [comment]
Additionally, if you could delete and ignore all the xml files which were added only for TeamCity builds, I will check if the configurations work.

**Comment by nikhilnanivadekar** [comment]
FWIW now the inspections builds are failing due to inspections violations. So, I think we are good 😄 
Let me know once you have removed all the xml files, I will check the builds and tweak the configurations accordingly.

**Comment by motlin** [comment]
Once we delete the iml and xml files, we'll lose the ability to reconfigure TeamCity, no?

**Comment by nikhilnanivadekar** [comment]
Didn’t follow your thought process about reconfiguring TeamCity builds. We *shouldnt* remove the *Inspections*.xml files. But all other Xmls which were historically added only for TeamCity, we should try to remove

**Comment by motlin** [comment]
@nikhilnanivadekar you said you fixed the inspections builds by reimporting them. That imports not just the inspection profiles, but the iml files. Once we delete them, clicking around in TeamCity and pressing reimport project will fail.

**Comment by nikhilnanivadekar** [comment]
That’s not what I did. I just removed the dependency of the imls in Inspection-4. You can check the logs for Inspection-1 where I have not removed the dependency those builds work as well. If you look at the build configs then it might make it clear.
Can you remove the unnecessary xml files and we can check if it works?
I think we are close to getting this working :)

**Comment by nikhilnanivadekar** [comment]
BTW seems like the build failures are seemingly legitimate from the log but I might be mistaken as I looked at it on the phone and might have missed something

**Comment by motlin** [comment]
I don't follow what you fixed? But poking around in the configs, it looks like maybe you changed the project type from IntelliJ to Maven, and only on profile 4. Is that right?

**Comment by nikhilnanivadekar** [comment]
Only on profile 4, yes. There is an option under IntelliJ build to not require iml files. I just disabled that and increased the memory. I tried with Maven build and that works as well

**Comment by motlin** [comment]
@nikhilnanivadekar that's excellent, that's the new information for me. Do you want me to update the other 3 profiles?

**Comment by nikhilnanivadekar** [comment]
Yes please go ahead. You might need to put the compiler.xml back in. I think that’s why the jmh test module is failing for compilation

**Comment by nikhilnanivadekar** [comment]
Heard back from JetBrains. Can you remove modules.xml? And convert to Maven project.

https://teamcity-support.jetbrains.com/hc/requests/2599837

**Comment by motlin** [comment]
I can't see that support link. Do you want to take over the branch again
from here?

**Comment by nikhilnanivadekar** [comment]
Sure will do

**Comment by nikhilnanivadekar** [comment]
Moved to #866

**Pull request closed without merging**
