### PR TITLE
Optimize toImmutable on primitive sets

### PR DESCRIPTION
**Pull request by mohrezaei**
Signed-off-by: Mohammad Rezaei <mohdev@rezaei.cc>

### CODE REVIEW

**Comment by mohrezaei** [comment]
what's the deal with the failing builds?

**Comment by nikhilnanivadekar** [comment]
No idea about Unit Test build. You can retry and it generally clears off. It’s an annoying GH action problem.
Ignore the EA builds for now. I’ll raise a PR over the weekend to address those.

**Review by donraab — APPROVED** [review]
LGTM. Thanks @mohrezaei !

**Comment by donraab** [comment]
Hi @mohrezaei, just curious on this code:

```
else
{
    mutableSet = new <name>HashSet(this.size());
    mutableSet.addAll(this);
}
```

Since this is in `IntHashSet`, would this be a better option?

```
else
{
    mutableSet = new <name>HashSet(this);
}

```

**Comment by mohrezaei** [comment]
@donraab the constructor that takes a set blindly copies the backing array (including all extra space). E.g. a set with enough room with 1000 elements that contains just 50 will have a lot of extra space in the backing array. A presized set with `addAll` will have the right amount of space in the backing array.

**Pull request merged**
