### PR TITLE
made it possible to get value from map using different from original key types but with the same equals and hashcode output

### PR DESCRIPTION
**Pull request by kolybelkin**
The idea is to use custom implementation of CharSequence as key (when it returns the same hashcode and it equals) for getting the value associated with String key. Currently it works for general case in get method but does not work if slowGet method is involved.

### CODE REVIEW

**Comment by mohrezaei** [comment]
Why doesn't it work with `slowGet`?

**Comment by kolybelkin** [comment]
If the original key is String object, then it is possible to use only String type as a key because equals method of String has only one condition for comparing - obj instanceof String

**Comment by mohrezaei** [comment]
I understand the reason you're reversing the call order. What I don't understand is, you've reversed the call order in `slowGet`, and yet you said:

> Currently it works for general case in get method but does not work if slowGet method is involved.

**Comment by kolybelkin** [comment]
Take a look at get method, the call order is already reversed there for the case with no resizing (no slowGet call)

**Comment by mohrezaei** [comment]
Sorry, I understand now. I misread your statement.

The changes are fine. Please add test cases for all the changed methods (using CharSeq/String).

**Comment by nikhilnanivadekar** [comment]
@kolybelkin any updates on this? I see that @mohrezaei had asked for tests before merging this PR. Can you please add tests? Please let us know if you need help.

**Comment by kolybelkin** [comment]
Hi, I am working on it currently and do not have time for unit tests, sorry
11 февр. 2020 г., 19:08 +0400, Nikhil Nanivadekar <notifications@github.com>, писал:

**Comment by kolybelkin** [comment]
Not working
11 февр. 2020 г., 19:08 +0400, Nikhil Nanivadekar <notifications@github.com>, писал:

**Comment by motlin** [comment]
Should we add a ConcurrentHashingStrategyMap?

**Comment by nikhilnanivadekar** [comment]
Closing due to inactivity

**Pull request closed without merging**
