### PR TITLE
Fix Javadoc warnings

### PR DESCRIPTION
**Pull request by kedar-joshi**
Signed-off-by: Kedar Joshi <kdar_joshi@yahoo.com>

Please see https://github.com/eclipse/eclipse-collections/issues/808#issuecomment-596024912.

### CODE REVIEW

**Comment by kedar-joshi** [comment]
@nikhilnanivadekar Currently CI build for Javadoc is failing for this PR. Once gh-816 is merged and this is rebased, which should take care of the build failure.

**Comment by nikhilnanivadekar** [comment]
@kedar-joshi I have merged #816 . Thanks for your help!
Before I merge this PR, can you please reword the commit to say Fixes #808 ?
Additionally, on this same PR but a different commit, can you please delete the row in Travis.yaml which allows failure for Javadoc build. You need to essentially delete this: https://github.com/eclipse/eclipse-collections/blob/514c7df7b78fa3dd559170249aeabd5089ba11cd/.travis.yml#L76
to Line 79.

**Comment by kedar-joshi** [comment]
> Before I merge this PR, can you please reword the commit to say Fixes #808 ?
Done.

> can you please delete the row in Travis.yaml which allows failure for Javadoc build ..
Done.

**Comment by nikhilnanivadekar** [comment]
@kedar-joshi great thanks! This looks good to me. I think `Verify` still needs a fix:

```
2 warnings
15:24:51:304 [WARNING] Javadoc Warnings
15:24:51:304 [WARNING] /home/travis/build/eclipse/eclipse-collections/eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java:150: warning: empty <p> tag
15:24:51:304 [WARNING] * <p>
15:24:51:304 [WARNING] ^
15:24:51:304 [WARNING] /home/travis/build/eclipse/eclipse-collections/eclipse-collections-testutils/src/main/java/org/eclipse/collections/impl/test/Verify.java:168: warning: empty <p> tag
15:24:51:305 [WARNING] * <p>
15:24:51:305 [WARNING] ^
```

**Comment by kedar-joshi** [comment]
@nikhilnanivadekar Yes, you are right. Not sure how I missed those ? I will fix it ASAP.

Quick question, Actual code contains 79 other instances which should generate same warning but somehow doesn't. So while I'm at this, shall I fix those as well ?

**Comment by nikhilnanivadekar** [comment]
Good call. Please fix those! Thank you very much!

**Comment by kedar-joshi** [comment]
>  I think Verify still needs a fix:

Fixed.

**Comment by nikhilnanivadekar** [comment]
LGTM. Thanks for your contribution!

**Pull request merged**
