### PR TITLE
Upgrade CheckStyle from 8.18 to 8.29.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@motlin I tried doing this as well. Something weird is going on with the checkstyle plugin:

```
18:38:04:371 [ERROR] Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1 or one of its dependencies could not be resolved: Failure to find org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.1 in https://maven-central.storage-download.googleapis.com/repos/central/data/ was cached in the local repository, resolution will not be reattempted until the update interval of google-maven-central has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1 or one of its dependencies could not be resolved: Failure to find org.apache.maven.plugins:maven-checkstyle-plugin:jar:3.1.1 in https://maven-central.storage-download.googleapis.com/repos/central/data/ was cached in the local repository, resolution will not be reattempted until the update interval of google-maven-central has elapsed or updates are forced
```

**Comment by nikhilnanivadekar** [comment]
oh and the weird part is that it only fails on Travis 🤷‍♂️

**Comment by motlin** [comment]
Since this passes in GitHub actions and fails in Travis, should we merge it and start disabling travis builds starting with checkstyle? @nikhilnanivadekar ?

**Comment by donraab** [comment]
Start removing the duplicate builds from Travis in a separate PR and then rebase and submit this one again.

**Comment by nikhilnanivadekar** [comment]
+1

**Comment by nikhilnanivadekar** [comment]
can rebase and check if now the builds are passing?

**Comment by donraab** [comment]
The builds are all passing except for Travis which is queued. But since Travis no longer runs a checkstyle build, I believe this is fine to merge. So feel free to merge @motlin if you have rebased.

**Pull request merged**
