### PR TITLE
Update 3-Code_Blocks.adoc

### PR DESCRIPTION
**Pull request by Ocheretovich**
Update 3-Code_Blocks

### CODE REVIEW

**Comment by donraab** [comment]
Hi @Ocheretovich, looks like from the builds that you need to sign the CLA with the Eclipse Foundation.

**Comment by Ocheretovich** [comment]
> Hi @Ocheretovich, looks like from the builds that you need to sign the CLA with the Eclipse Foundation.

Hello. So I signed the agreement, but for some reason on github, it shows as unsigned

**Review by donraab — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by donraab** [comment]
Hi @Ocheretovich, the change looks good, and the eca check is now passing, but I see you have merge commit. Please rebase your PR on top of the current master.

https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#pull-requests

Thanks!

**Comment by Ocheretovich** [comment]
Always happy to catch up with you. But I have a problem, since I'm new to this thread, unfortunately I can't rebase my PR on top of the current master branch. Maybe I'll delete my request pool and create a new one, what do you say? thanks for understanding

**Comment by donraab** [comment]
Hi @Ocheretovich, if you haven't done a rebase before, this is a great article for first time contributors to Eclipse Collections to read. It explains in "5. The Next Step" how to setup a remote repository as `upstream` and do a `git rebase upstream/master` followed by a` git push -f`.

https://mydeveloperplanet.com/2021/01/20/how-to-start-contributing-to-open-source/

Hope this helps. Worst case if you close your PR and submit a new one that will always work.

**Comment by Ocheretovich** [comment]
I'm sorry for wasting your precious time, I see that you are a great professional in your field, and I appreciate that you want to teach me how to work. But, unfortunately, I submitted my pool request through the <change file> tab on Github, and therefore I do not have any skills at all to work through the terminal and the term command

**Comment by donraab** [comment]
No worries, and thank you for providing the context for your change. In that case, delete your PR and create a new one with the same change and I can approve and merge.

**Comment by Ocheretovich** [comment]
Thank you, you are a very good and educated man

**Pull request closed without merging**
