### PR TITLE
Add specialized forEachKey(ValueType) methods to List/Set/BagMultimap…

### PR DESCRIPTION
**Pull request by donraab**
… leaf interfaces. Partially addresses #1104.

Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

### CODE REVIEW

**Comment by motlin** [comment]
It's possible to put these methods on quite a few more interfaces, like ListMultimap.

The tests ought to use static types that match the value collections, rather than `Iterable`.

I still think it makes more sense to use read-only types (like ListIterable) rather than mutable types that will throw if you call mutating methods (MutableList wrapped in unmodifiable wrapper).

WDYT?

**Comment by donraab** [comment]
I think both are useful. The question I have with the more abstract one is whether it is ok to not wrap the ListIterable in an unmodifiable collection and allow direct manipulation of the List in the Multimap by casting. Thoughts? If we think it is ok to cast and modify, then maybe wrapping the MutableList in an unmodifiable collection is unnecessary. 

But this is inconsistent with what we do in get today.

**Comment by motlin** [comment]
It’s not ok to cast and modify, because there’s other state that can get
out of sync, and it’s also possible to violate invariants, like the backing
map never contains empty value collections.

It would be ok to use mutable wrappers that support mutation by preserving
those invariants, but it’s a lot of work.

**Comment by donraab** [comment]
Ok, so we agree that my approach of returning an unmodifiable wrapper in the case of mutable collection returns make sense. I am currently working on adding higher level methods in this PR. It is a lot more work, and I am only doing this for ListIterable, SetIterable, Bag for now since I had already done the work for the mutable and immutable versions of these types. If we like the approach, then I will work in a separate PR to finish the others.

**Comment by motlin** [comment]
sounds good!

**Comment by donraab** [comment]
@motlin, I backed out my changes for the abstract methods. I was up to 40 files changed and felt the change was too large and complicated to review. The problem with adding the more abstract methods is that they start intersecting with sorted and unsorted varieties of `Multimap`. I would suggest this be done as a separate PR as it will be easier to review and find issues. I made the changes you suggested in the tests using concrete types instead of `Iterable`.

**Review by motlin — APPROVED** [review]
Makes sense, LGTM!

**Comment by donraab** [comment]
Thank you for the review @motlin. I just updated a few of the copyrights and will wait for the builds to pass and then I'll merge.

**Pull request merged**
