### PR TITLE
Add withInitialCapacity() to primitive List and Set factories

### PR DESCRIPTION
**Pull request by fipro78**
Signed-off-by: Dirk Fauth <dirk.fauth@googlemail.com>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
On another thought, if we want it in 10.3.0, @fipro78 can you add default implementation which throws

‘throw new UnsupportedOperationException(“Default method to ensure backwards compatibility”)’

I’ll leave it to @fipro78 to decide how to proceed.

**Comment by fipro78** [comment]
You mean the interface should add the method as a default method?

**Comment by nikhilnanivadekar** [comment]
Exactly, because 10.3.0 is a minor version, we cannot break API.

**Comment by fipro78** [comment]
> Exactly, because 10.3.0 is a minor version, we cannot break API.

Sorry, totally missed the breaking change while working in the template. I updated the PR. Hope it is fine now.

**Comment by donraab** [comment]
Hi @fipro78 , the changes look good to me. Please rebase and squash your commits and I will merge. Thanks!

**Comment by donraab** [comment]
Merged. Thank you for the contribution @fipro78!

**Pull request merged**
