### PR TITLE
Upgrade tycho plugin from 1.2.0 to 1.7.0

### PR DESCRIPTION
**Pull request by nikhilnanivadekar**
This is to try and fix the JDK 15 Build.

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Raised issues for EBR and Tycho:

1) https://bugs.eclipse.org/bugs/show_bug.cgi?id=563766

2) https://bugs.eclipse.org/bugs/show_bug.cgi?id=563758

**Comment by nikhilnanivadekar** [comment]
@guw seems like EBR is not co-operating with Java 15. I have raised bugs for tracking.

**Comment by nikhilnanivadekar** [comment]
Pinging @guw again to see if he can help with EBR failures with Java 15.

**Comment by guw** [comment]
@nikhilnanivadekar We have support for Tycho 1.7 now. I've marked the JDK 15 bug as 'helpwanted'. I don't have cycles to look into this anytime soon. We are still on JDK 11 LTS.

**Comment by nikhilnanivadekar** [comment]
Thank you very much! I’ll upgrade Tycho to 1.7. Regarding Java 15, we’ll skip the p2 module and reinclude it once Java 15 is working fine.
If I get time, I can try to contribute for the JDK 15 fix. Cheers!

**Comment by nikhilnanivadekar** [comment]
@donraab I think the GitHub actions are hanging for this PR. I do not know why. But I see that Unit Tests 8 has passed and Unit Tests 14 has passed. I guess it should be enough to merge this PR. I will be creating a milestone release once this is merged, so at that time the p2 repo will be validated any case. Thoughts?

**Comment by guw** [comment]
@nikhilnanivadekar See eclipse/ebr/pull/39 for Java 15 update. We are waiting on an ASM update with support for Java 15.

**Comment by nikhilnanivadekar** [comment]
Thanks @guw I’ll be on the lookout for that PR to be closed. Thanks for your help and support!

**Pull request merged**
