### PR TITLE
Use try-with-resources

### PR DESCRIPTION
**Pull request by diffblue-assistant**
This pull request was created automatically as part of our ongoing efforts
at https://diffblue.com to implement refactorings. Feel free to leave feedback
here or contact us directly for any enquiries.

The developer in charge is @krobelus.

**Changes**:

- Replace try statements that close a resource in the finally block with a
try-with-resources statement [1].

[1] https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@krobelus
1) The ip validation is failing, since the commit needs to be signed off
2) Please update the commit message to be more explanatory like "Use try with resources in SerializerTestHelper"
3) For now we will ignore the failure in Java 11 build

**Comment by krobelus** [comment]
@nikhilnanivadekar Thanks for your feedback, I have signed off the commit and modified the commit message.

I wonder what's the reason for the build failure with Java 11.

**Comment by nikhilnanivadekar** [comment]
most likely it might be because the surefire plugin is not compatible with Java 11. I will take a look later this week to find the root cause.

**Comment by nikhilnanivadekar** [comment]
@krobelus Can you please rebase on to master? I will merge after that. Thanks!

**Comment by diffblue-assistant** [comment]
@nikhilnanivadekar I just rebased, thanks!

**Comment by krobelus** [comment]
@nikhilnanivadekar I just rebase, thanks!

**Pull request merged**
