### PR TITLE
Update Tycho Version to 1.2.0

### LINKED ISSUE #535: Java 10, Java 11-EA builds failing due to EBR plugin
The Java 10 and Java 11-EA builds are failing due to API compatibility issue in the EBR plugin while creating OSGi artifacts.

Example log: https://api.travis-ci.org/v3/job/394162025/log.txt

```
21:19:47:456 [ERROR] Failed to execute goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle (default-bundle) on project org.eclipse.collections: Execution default-bundle of goal org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle failed: An API incompatibility was encountered while executing org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT:bundle: java.lang.ExceptionInInitializerError: null
21:19:47:456 [ERROR] -----------------------------------------------------
21:19:47:457 [ERROR] realm =    extension>org.eclipse.ebr:ebr-maven-plugin:1.0.0-SNAPSHOT
```

@guw @ujhelyiz Can either of you please help?

### PR DESCRIPTION
**Pull request by guw**
Fixes #535

Signed-off-by: Gunnar Wagenknecht <gunnar@wagenknecht.org>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@guw this has failed the OSGi for Java 10, 11-EA, I presume that upgrading the Tycho Version will be a part of Yak shaving? 
But since Tycho is used in OSGi builds, I want to confirm if you think the upgrade will not create red herrings in the changes that are required to fix the build.

**Comment by guw** [comment]
@nikhilnanivadekar I was hoping that upgrading Tycho would be sufficient. But I guess not. This PR is for fixing the build issue.

**Comment by nikhilnanivadekar** [comment]
alright I will hold off on merging this then

**Comment by guw** [comment]
@nikhilnanivadekar I released a fix to the EBR plug-in. I rebased the PR to kick-off a new build.

**Comment by guw** [comment]
@nikhilnanivadekar Can you help investigate the following build error:

```
$ ./.travis-command-ea-builds.sh
Downloading JDK from https://download.java.net/java/early_access/jdk11/16/BCL/jdk-11-ea+16_linux-x64_bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7073  100  7073    0     0   5228      0  0:00:01  0:00:01 --:--:--  5231
Extracting archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

It doesn't look related to OSGi.
https://travis-ci.org/eclipse/eclipse-collections/jobs/395590648

**Comment by nikhilnanivadekar** [comment]
@guw that happens when they release a new EA version and demise the old one. Give me 15 mins, I will research and update the correct coordinates. Thanks!

**Comment by nikhilnanivadekar** [comment]
The build has gone to success! Merging this PR. Thanks for the fix and contribution!

**Comment by nikhilnanivadekar** [comment]
@guw  the build is still failing with the same error as before, did the fix for EBR get reverted or something?

https://api.travis-ci.org/v3/job/395608107/log.txt

**Pull request merged**
