### PR TITLE
Add JDK 15-EA build and ignore iml files to gitignore which annoy contributors

### PR DESCRIPTION
**Pull request by nikhilnanivadekar**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Please note the build is failing on OSGi module. Most likely it is because Eclipse folks need to give a new version of the plugin. I will reach out to them. That said, it should not stop us from merging this as the builds are under "Allowed Failures"

**Comment by motlin** [comment]
Could you split this? The EA-15 stuff is a rubber-stamp approval. The *.iml stuff I don't agree with, and if I did, it's not ignored properly.

**Comment by nikhilnanivadekar** [comment]
@motlin Done. And raised a separate PR as well for gitignore.

**Comment by nikhilnanivadekar** [comment]
The build passed in my fork. Travis is backed up, it might take about 20+ hrs for it to catch up. So I’ll merge it now

**Pull request merged**
