### PR TITLE
Implement groupByEach Collector on Collectors2. Resolves #362

### LINKED ISSUE #362: Implement groupByEach Collector on Collectors2.

### PR DESCRIPTION
**Pull request by TheLoneKing**
Signed-off-by: TheLoneKing <dkumar.kovai@gmail.com>

### CODE REVIEW

**Comment by TheLoneKing** [comment]
@donraab I don't understand the _updating the copyrights_ part. Should I add my name as a contributor in the Copyright section? Is that it?

**Comment by donraab** [comment]
You can update the year to 2017 and add "and others." after the original copyright holder since this is a minor contribution to an existing file.

**Comment by TheLoneKing** [comment]
@donraab I hope the recent changes will fulfill your suggestions.

**Comment by donraab** [comment]
LGTM.  Thank you for the contribution!

**Pull request merged**
