### PR TITLE
Make sun.misc an optional Import-Package in OSGi metadata

### PR DESCRIPTION
**Pull request by fipro78**
Signed-off-by: Dirk Fauth <dirk.fauth@googlemail.com>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
I can merge this and create another milestone. Were you able to take a look at 10.3.0 milestone to see if that works fine. If not then we can address more fixes before M4. Once all the p2 related problems are sorted out I’ll release 10.3.0

Thanks a ton for your help @fipro78 your expertise has helped us make the product better for the Eclipse ecosystem!

**Comment by fipro78** [comment]
I tested the milestone p2 repo and it looks good. I also tested consuming from a plain maven based osgi project and noticed the issue with sun.misc. Can verify with the next milestone :)

**Comment by nikhilnanivadekar** [comment]
Perfect! Thanks! Let me trigger M4 now

**Comment by fipro78** [comment]
> Thanks a ton for your help @fipro78 your expertise has helped us make the product better for the Eclipse ecosystem!

Your welcome! I think this is how open source works! :)

And with about my expertise ... well if I would be such an expert, we would not have needed that much iterations. :) Anyhow, glad the changes help in making Eclipse Collections even more and easier consumeable in various project scenarios.

**Pull request merged**
