### PR TITLE
Fixes override methods on MutableOrderedMap #517

### PR DESCRIPTION
**Pull request by brenopessoa**
Hello everyone, i tried resolve the issue #517

Signed-off-by: Breno Pessoa <brenopessoamelo@gmail.com>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@brenopessoa this looks good to me. However, can you please update the commit message to say Fixes #517 .
GitHub auto-closes the issues if the commit has keywords like Fixes or Closes followed by the issue number. Refer to this doc for details: https://help.github.com/articles/closing-issues-using-keywords/

Thanks for the contribution!

**Comment by nikhilnanivadekar** [comment]
To make it explicit, I would suggest a commit message like this:
"Override methods on MutableOrderedMap. Fixes #517 ."

**Comment by brenopessoa** [comment]
Thank you so much for the tip, im fixing.

**Comment by nikhilnanivadekar** [comment]
Thanks for the contribution! LGTM 👍 
Merged!

**Pull request merged**
