### PR TITLE
Minor fixes in the Greek translation

### PR DESCRIPTION
**Pull request by thodorisbais**
Signed-off-by: Thodoris Bais <thodoris.bais@gmail.com>

changes requested in #783

### CODE REVIEW

**Comment by thodorisbais** [comment]
@nikhilnanivadekar could you have a look at it now? I'm not sure whether I fulfilled your last two points on #783

**Comment by nikhilnanivadekar** [comment]
I will merge these changes. There are couple of minor fixes required but it is easier to do them than describe as explaining exactly what needs to change. I will raise a PR with those small changes and have you take a look. Cheers!
Thanks for your contribution! Happy New Year! 😄 🍾 🎉

**Comment by nikhilnanivadekar** [comment]
@thodorisbais Take a look at #785

**Comment by thodorisbais** [comment]
Oh, yes! Apparently, I was too impatient for this New Year's Eve :-) 
Thanks a lot and Happy 2020!

**Pull request merged**
