### PR TITLE
Turn on CheckStyle rule ArrayTrailingComma and fix violations.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by donraab** [comment]
Hi @motlin, I don't understand the purpose of this, and how adding a trailing comma is the fix. Can you explain please?

**Comment by motlin** [comment]
@donraab CheckStyle's documentation [says](https://checkstyle.sourceforge.io/config_coding.html#ArrayTrailingComma):

Rationale: Putting this comma in makes it easier to change the order of the elements or add new elements on the end. Main benefit of a trailing comma is that when you add new entry to an array, no surrounding lines are changed.

```
{
  100000000000000000000,
  200000000000000000000, // OK
}

{
  100000000000000000000,
  200000000000000000000,
  300000000000000000000,  // Just this line added, no other changes
}
```

**Comment by donraab** [comment]
@motlin TeamCity builds seem to be queued and not moving. I'll merge this one as all the non-duplicate builds have passed.

**Comment by motlin** [comment]
Rebased. 0 TeamCity agents are running.

**Comment by donraab** [comment]
@motlin Thanks for rebasing... merging as all of the builds TC passed previously.

**Pull request merged**
