### PR TITLE
Delete default implementations that were added for backwards compatibility.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Looping in @donraab , @mohrezaei 
I really wanted to remove the default implementations which just throw. But seems like we have users who will start breaking. That is why I had shelved the work I did on this.

**Comment by mohrezaei** [comment]
what prevents these from being properly implemented in the default implementation?

**Comment by nikhilnanivadekar** [comment]
they need dependencies from eclipse-collections-impl

**Comment by mohrezaei** [comment]
I assume that's just for construction? If so, can a little bit of reflection deal with that?

**Comment by motlin** [comment]
I have this idea I've been meaning to try forever. If the collection factories registered themselves with Java's ServiceLocator, we could move Lists, Sets, Maps (the factories) into api. Then a whole bunch more behavior could live in the interfaces.

**Comment by nikhilnanivadekar** [comment]
@motlin I think this PR can be reopened. I think it is fine to break backwards compatibility. I will mention it in the release notes with all the methods for which default implementations were removed. After all new API is being added without default implementation which throws, so backwards compatibility will already be broken.
@donraab @mohrezaei thoughts?

**Comment by mohrezaei** [comment]
I like @motlin's idea of using the ServiceLocator. It allows a decent default implementation of these methods and furthermore, makes it a lot easier for EC users to use EC interfaces for their own collections.

**Comment by mohrezaei** [comment]
Maybe we could open an issue for the ServiceLocator as a prerequisite of adding these implementations.

**Comment by nikhilnanivadekar** [comment]
In my mind ServiceLocator can be picked up in minor release, but removing default methods is a major release change. So, I would rather remove these default implementations and then do the ServiceLocator of the same release or a future release.
The breaking change will be at compile time, with an auto-fix using the IDE, so I am less worried.

**Comment by mohrezaei** [comment]
I think the point is, once we do the ServiceLocator, we'll put these methods back, so why remove them now and cause trouble for our users?
You're right that the ServiceLocator can be released in a minor version. Interestingly, so can the actual implementation of these default methods.

**Pull request closed without merging**
