### PR TITLE
Optimize factory method to not create redundant array copies. 

### LINKED ISSUE #217: Optimize org.eclipse.collections.impl.list.immutable.ImmutableListFactoryImpl#withAll to not create redundant array copy.
The call `this.of((T[]) Iterate.toArray(items))` eventually creates an extra array copy before calling the constructor org.eclipse.collections.impl.list.immutable.ImmutableArrayList#newListWith. 
Similar observation for org.eclipse.collections.impl.list.immutable.ImmutableListFactoryImpl#withList.

### PR DESCRIPTION
**Pull request by nikhilnanivadekar**
Fixes #217.

### CODE REVIEW

**Comment by motlin** [comment]
Do we have JMH tests that show an improvement? I'm especially interested in the part that uses an iterator. Overall looks good.

**Comment by nikhilnanivadekar** [comment]
Benchmark  | Mode | Cnt | Score | Error | Units
-----------|------|-----|-------|-------|-------
fixedSizeOld1_Iterable | thrpt | 40 | 4858102.996 | ± 66349.497 | ops/s
fixedSizeNew1_Iterable | thrpt | 40 | 6390676.914 | ± 55234.917 | ops/s
fixedSizeOld1_List | thrpt | 40 | 13563612.411 | ± 54263.016 | ops/s
fixedSizeNew1_List | thrpt | 40 | 13540608.601 | ± 67201.530 | ops/s
fixedSizeOld2_Iterable | thrpt | 40 | 4427752.642 | ± 51203.852 | ops/s
fixedSizeNew2_Iterable | thrpt | 40 | 4495908.927 | ± 23049.528 | ops/s
fixedSizeOld2_List | thrpt | 40 | 10972536.907 | ± 58562.549 | ops/s
fixedSizeNew2_List | thrpt | 40 | 10230242.315 | ± 81199.485 | ops/s
fixedSizeOld3_Iterable | thrpt | 40 | 122.436 | ± 3.723 | ops/s
fixedSizeNew3_Iterable | thrpt | 40 | 115.706 | ± 9.447 | ops/s
fixedSizeOld3_List | thrpt | 40 | 129.313 | ± 13.266 | ops/s
fixedSizeNew3_List | thrpt | 40 | 120.029 | ± 0.863 | ops/s
immutableOld1_Iterable | thrpt | 40 | 4686992.874 | ± 23353.474 | ops/s
immutableNew1_Iterable | thrpt | 40 | 3749178.370 | ± 13708.387 | ops/s
immutableOld1_List | thrpt | 40 | 15144842.471 | ± 362402.596 | ops/s
immutableNew1_List | thrpt | 40 | 16400747.050 | ± 93450.370 | ops/s
immutableOld2_Iterable | thrpt | 40 | 3157600.643 | ± 65227.846 | ops/s
immutableNew2_Iterable | thrpt | 40 | 3099772.057 | ± 13250.902 | ops/s
immutableOld2_List | thrpt | 40 | 10358578.595 | ± 78896.783 | ops/s
immutableNew2_List | thrpt | 40 | 10400663.568 | ± 63968.306 | ops/s
immutableOld3_Iterable | thrpt | 40 | 128.690 | ± 3.084 | ops/s
immutableNew3_Iterable | thrpt | 40 | 104.348 | ± 0.677 | ops/s
immutableOld3_List | thrpt | 40 | 220.772 | ± 6.732 | ops/s
immutableNew3_List | thrpt | 40 | 236.550 | ± 2.150 | ops/s

Attached is the code I used for tests. The performance change is not very different, in some cases the performance has degraded, but that might be due to machine drift.

[ListConstructorTest.txt](https://github.com/eclipse/eclipse-collections/files/887223/ListConstructorTest.txt)

**Comment by nikhilnanivadekar** [comment]
@motlin should we merge this or leave the constructors as it is?

**Comment by nikhilnanivadekar** [comment]
@motlin , @donraab should we merge this? From the JMH tests, there are no gains, but I think it is the right thing to do. 
If we do not want to merge, then I am fine closing the PR. If we will merge, I will rebase.

**Pull request closed without merging**
