### PR TITLE
Remove Apache Felix plugin, Add Java 9 regression build

### PR DESCRIPTION
**Pull request by nikhilnanivadekar**
1) Remove Apache Felix plugin:
Removal of Apache Felix plugin will result in OSGi bundles not exported under eclipse-collections, eclipse-collections-api. However, these bundles are exported in p2 repository. Users should start using the same.
This will reflect in the release notes.

This is a compatibility breaking change.

2) Java 9 Regression builds

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
#226 has discussion about removing these obsolete bundles

**Comment by nikhilnanivadekar** [comment]
@guw , @kthoms to confirm from our previous discussion, it is ok to not publish the OSGi bundles since, the p2 repo will have the necessary packages? 
What about non-eclipse OSGi users? Or there is no such thing as non-eclipse OSGi users, and one needs eclipse to use OSGi? 

Asking since, I am not an OSGi user/expert.

Thanks!

**Comment by guw** [comment]
Yes, there is no need to add OSGi meta-data to the regular jars. non-p2 OSGi users can consume the bundle via direct download right away. However, you could also mvn deploy the OSGi bundle and have it available from Maven Central.

**Comment by nikhilnanivadekar** [comment]
@guw what are the deploy steps to maven central? I would prefer doing that as well.

**Comment by nikhilnanivadekar** [comment]
Raised @294 for tracking.

**Pull request merged**
