### PR TITLE
Add unit tests for CounterProcedure class

### LINKED ISSUE #987: Test Coverage: CounterProcedure
`CounterProcedure` currently has 0% test coverage. Add unit tests for this class.

### PR DESCRIPTION
**Pull request by vishalkarmalkar**
Resolves #987

Signed-off-by: Vishal Karmalkar <vishal.karmalkar@gmail.com>

### CODE REVIEW

**Comment by vishalkarmalkar** [comment]
@nikhilnanivadekar Being my first PR can you please let me know if I have followed the guidelines correctly? I deliberately kept this PR small to ensure I see it through end to end correctly before submitting more PR's

**Comment by vishalkarmalkar** [comment]
@nikhilnanivadekar I am fixing the build failures. Is there any concept of pre commit build here to confirm my fix will indeed fix the build before actually committing it?

**Comment by nikhilnanivadekar** [comment]
When you fork the repo, you get a complete copy of the repo under your name. Each time you push code, etc to your repo, GitHub will trigger actions and builds on your fork as well. So check the builds in your fork, once it’s green you can raise a PR.
Once you have raised a PR each time you push to the same branch, GitHub will update the PR and run builds on the PR as well as your fork. Hope this helps

**Comment by vishalkarmalkar** [comment]
@nikhilnanivadekar Makes sense.

Noob question - Where can I check under my fork that builds are green? I think I checked all the tabs but cant seem to find it :)

https://github.com/vishalkarmalkar/eclipse-collections

**Comment by nikhilnanivadekar** [comment]
There should be an actions tab similar to this: https://github.com/eclipse/eclipse-collections/actions

**Comment by nikhilnanivadekar** [comment]
This is a new step on GitHub that first time contributors need their GitHub workflows to be approved. I have just approved it and now builds are running.
Can you please rebase and squash the commits? 
https://garrytrinder.github.io/2020/03/squashing-commits-using-interactive-rebase

I can merge it once the commits are squashed and all builds pass

**Comment by prathasirisha** [comment]
@vishalkarmalkar There is also another PR that is open for adding tests in the same package that you are currently working on!
 
Sharing the link, so you don't spend time writing the same tests covered here - https://github.com/eclipse/eclipse-collections/pull/1113. Hope this helps!

**Comment by vishalkarmalkar** [comment]
> @vishalkarmalkar There is also another PR that is open for adding tests in the same package that you are currently working on!
> 
> Sharing the link, so you don't spend time writing the same tests covered here - #1113. Hope this helps!

@prathasirisha Thank you. I was not aware that the class was covered in tests in a different PR. Since I didnt see any PR linked to the original issue I started working on it.

@nikhilnanivadekar is going to walk me through some of the branching issues I am facing and after that will let you/nikhil decide if my PR needs to be kept or can be deleted (as we will run into merge conflicts eventually I guess)

**Comment by prathasirisha** [comment]
Closing this PR as this was already covered in this PR https://github.com/eclipse/eclipse-collections/pull/1113. 

@vishalkarmalkar last time we spoke offline, I remember you were running into issues with git and rebase. I will be happy to help with your next contribution if you start fresh and pick up a different issue. Thank you for taking an interest in this project, and looking forward to your future contributions! 😄

**Pull request closed without merging**
