### PR TITLE
Upgrade IntelliJ code style settings.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by motlin** [comment]
Yes, especially for whether parens appear on their own lines or not.

**Comment by donraab** [comment]
> Yes, especially for whether parens appear on their own lines or not.

Ok, cool.  Rebase and I will merge.

**Comment by motlin** [comment]
@donraab rebased

**Comment by donraab** [comment]
I'm going to merge this and I'll take a look at the new GitHub Actions build that is failing. I think it's probably as simple as changing 14-ea to 14 now that JDK 14 is released.

**Pull request merged**
