### PR TITLE
Fix #428. Wildcard type in MutableMapIterable#putPair & add methods.

### LINKED ISSUE #428: class of argument in MutableMapIterable#putPair class to be Pair<? extends K, ? extends V>
Hi all, 

I suggest to change class of argument in MutableMap#putPair to be Pair<? extends K, ? extends V> instead of Pair<K, V> so that the function allow to put Pair object with subclass of K, V.

Thanks,
Tsuyoshi.

### PR DESCRIPTION
**Pull request by henohenotsuyoshi**
This is for issue https://github.com/eclipse/eclipse-collections/issues/428

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Should the modification methods in `MutableMultimap` also change?

`default boolean add(Pair<K, V> keyValuePair)`
`default boolean putAllPairs(Pair<K, V>... pairs)`
`default boolean putAllPairs(Iterable<Pair<K, V>> pairs)`

I can be a different PR.

**Comment by nikhilnanivadekar** [comment]
@henohenotsuyoshi can you please rebase on to master? Also, update the commit message to have Fixes or Resolves for the original issue: #428

**Comment by henohenotsuyoshi** [comment]
I just rebased it. Thanks.

**Comment by motlin** [comment]
@nikhilnanivadekar 

Yes, this method should also change:
```java
default boolean add(Pair<K, V> keyValuePair)
```

I doubt these can be changed due to limits in the Java type system.
```java
default boolean putAllPairs(Pair<K, V>... pairs)
default boolean putAllPairs(Iterable<Pair<K, V>> pairs)
```

**Pull request merged**
