### PR TITLE
Add check on FastList for initialCapacity < 0 #365

### PR DESCRIPTION
**Pull request by henohenotsuyoshi**
This is for issue https://github.com/eclipse/eclipse-collections/issues/365 

Signed-off-by: sone tsuyoshi <Tsuyoshi.Sone@gs.com>

### CODE REVIEW

**Comment by motlin** [comment]
Thanks for the contribution. I would suggest adding context to the error
message, specifically the illegal parameter.

```
throw new IllegalArgumentException("Expected initial capacity greater than
or equal to 0. Was: " + initialCapacity);
```

**Comment by nikhilnanivadekar** [comment]
@henohenotsuyoshi thanks for the contribution. In addition to the comments from @motlin this is a compatibility breaking change and we will have to wait for major version development to start. I will ping on this PR once the major version target opens. Thanks for your patience and understanding!

**Comment by henohenotsuyoshi** [comment]
@motlin, @nikhilnanivadekar Make sense. I just updated my branch.

**Comment by nikhilnanivadekar** [comment]
@henohenotsuyoshi 10.0.0 target is open, can you please rebase so that we can merge this request.
Also, please update the commit message to say Fixes or Resolved #365 so that GitHub will auto-close the issue. Thanks!

**Comment by henohenotsuyoshi** [comment]
I just rebased the branch& updated commit message. Thanks!

**Pull request merged**
