### PR TITLE
Implement UnmodifiableMutableOrderedMap.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
1) Please update the copyrights.
2) Secondly, I always miss/forget this, so please remind me, don't we want our Unmodifiable data structures to return unmodifiable on operation? For Example: select() should return an UnmodifiableMap?

**Comment by motlin** [comment]
Unmodifiable wrappers are interesting in that they already violate their
own interface, in that they aren't mutable. If we changed the methods like
select() to return unmodifiable, but mutable collections, that would be a
much more confusing violation of the api, to the point where you might as
well just call the thing immutable. Anyway, we're very consistent.
Unmodifiable and Synchronized wrappers have methods that never return
wrappers. Only their views (like keySet) are wrapped the same way.

**Comment by nikhilnanivadekar** [comment]
ok makes sense! thank you!

**Comment by nikhilnanivadekar** [comment]
@motlin may be there should be a blog about, how and why the decision was made. It is interesting problem to have and solve.

**Comment by motlin** [comment]
done

**Comment by nikhilnanivadekar** [comment]
Merging this even though TC builds are failing as an active branch is not created on TC since this is an old PR (I think).

**Pull request merged**
