### PR TITLE
Bug Fix for Primitive Maps with Hashing Strategy

### PR DESCRIPTION
**Pull request by jajodr**
Signed-off-by: jajodr <ranjan.jajodia@gs.com>

### CODE REVIEW

**Comment by itohro** [comment]
Forgot to mention to you. Could you do this on 7.0.x branch and submit PR against 7.0.x branch? 

We'll merge it to master afterwards.

**Comment by jajodr** [comment]
Ok sure. Does the request look ok otherwise?

**Comment by jajodr** [comment]
I am not quite sure about the signed commit part. Intellij doesn't support
it so had to use an external git GUI for local commit.

**Comment by itohro** [comment]
You see ip validation in this PR is successful, so the sign part should be fine. Let me review the code tomorrow.

**Comment by motlin** [comment]
Closing since this is superseded by #54.

**Pull request closed without merging**
