### PR TITLE
Fixes generated Eclipse features #763

### PR DESCRIPTION
**Pull request by ujhelyiz**
* Ensures the correct EPLv1 license is downloaded
 * Turns off signing for the feature

Signed-off-by: Zoltan Ujhelyi <zoltan.ujhelyi@incquerylabs.com>

### CODE REVIEW

**Comment by ujhelyiz** [comment]
An important note about the change: feature signing is always turned on. For this reason, the build can only be executed on the Jenkins instance of the Eclipse Foundation. If necessary, the signing can be moved to a profile where it can be disabled.

I have created a test configuration using the Jenkins instance for the VIATRA project: https://download.eclipse.org/collections/10.0.0/repository/

**Comment by nikhilnanivadekar** [comment]
@ujhelyiz thanks for the fix. I will merge this PR.
I am slightly confused about the configuration change which needs to be done to sign the artifacts. I remember last year, you had helped me fix the signing issue by adding parameters to Jenkins. 
I have reached out to you offline and I need help to figure out what needs to change on Jenkins. I apologize for my lack of knowledge.

**Comment by ujhelyiz** [comment]
As far as I can tell, no configuration change is necessary to run the modified build - the updates should work exactly the same way as before (given you generate the feature and p2 repository on ci.eclipse.org).

**Comment by nikhilnanivadekar** [comment]
Merging because travis failure was due to JDK 13 being unavailable in the docker image.

**Pull request merged**
