### PR TITLE
Upgrade versions of library dependencies.

### PR DESCRIPTION
**Pull request by motlin**
- Upgrade JMH from 1.19 to 1.21.
- Upgrade HPPC from 0.7.2 to 0.8.1.
- Upgrade Guava from 21.0 to 25.1-jre.
- Upgrade Scala from 2.11.7 to 2.12.6.
- Upgrade version of commons-codec from 1.10 to 1.11.

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
This has changes to the libraries/*.xml files. We already have a few concerns about the project files.

**Comment by motlin** [comment]
Yeah, but that's because they've become stale over the last year. Let's
just fix them.

**Comment by motlin** [comment]
Let's merge #590 first, and then I'll rebase this on top.

**Comment by nikhilnanivadekar** [comment]
done

**Pull request merged**
