### PR TITLE
Add test for SumOfPrimitiveProcedure

### PR DESCRIPTION
**Pull request by szatyinadam**
Add test for SumOfShortProcedure.
Related issue: #991

### CODE REVIEW

**Comment by donraab** [comment]
Hi @szatyinadam, SumOfShortProcedure is a generated class. We would want tests for all of the primitive types (SumOfLongProcedure, SumOfDoubleProcedure, etc.) You can look into generating a test class for all of the types. I explain a little bit about how the code generation for primitive types works in Eclipse Collections here:

https://stackoverflow.com/questions/61386226/resources-for-understanding-fastutil-internals/61400271#61400271

**Comment by szatyinadam** [comment]
@donraab Sorry for the late response and thanks for the explanation. Can You take another look on the updated PR?

**Comment by prathasirisha** [comment]
Hi  @szatyinadam, changes look good to me. But before I can merge your changes, could you please squash your 2 commits to 1 commit. Also can you amend your commit message to include the issue number. You can add Resolves #<issue> at the end of your commit message. 

Please let me know if you have questions. Thank you for your contribution!

**Comment by szatyinadam** [comment]
@prathasirisha Sure, I did it.

**Comment by prathasirisha** [comment]
> @prathasirisha Sure, I did it.

Hi, @szatyinadam apologize for not noticing this sooner. But you are 66 commits behind the main repo, can you please rebase your PR.

**Comment by szatyinadam** [comment]
@prathasirisha can you take another look on it now?

**Review by prathasirisha — APPROVED** [review]
Thank you for your contribution! :)

**Pull request merged**
