### PR TITLE
Fix generics on MultiReaderFastList newList. Fixes #368

### LINKED ISSUE #368: Fix generics on MultiReaderFastList newList
Change:
`public static <T> MultiReaderFastList<T> newList(Iterable<T> iterable)`

To:
`public static <T> MultiReaderFastList<T> newList(Iterable<? extends T> iterable)
`
Remove this cast at the same time in MultiReaderMutableListFactory:
```
    @Override
    public <T> MutableList<T> withAll(Iterable<? extends T> iterable)
    {
        return MultiReaderFastList.newList((Iterable<T>) iterable);
    }
```

### PR DESCRIPTION
**Pull request by nolequen**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@nolequen thank you for the contribution. This is an API breaking change, so we will merge it when the target for 10.0 opens next year. I will comment on this PR. Thanks for your patience and understanding!

**Comment by nolequen** [comment]
@nikhilnanivadekar great! thanks!

**Comment by nikhilnanivadekar** [comment]
@nolequen 10.0.0 target is open. Can you please rebase on to master?

**Comment by nolequen** [comment]
@nikhilnanivadekar done.

**Comment by nikhilnanivadekar** [comment]
@nolequen Thanks for the contribution!
Merged.
We have more open issues which are labeled as "good first issue" if you would like to contribute: https://github.com/eclipse/eclipse-collections/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by nolequen** [comment]
@nikhilnanivadekar thank you too!

**Pull request merged**
