### PR TITLE
Correct versions in p2-feature and repository

### PR DESCRIPTION
**Pull request by fipro78**
Signed-off-by: Dirk Fauth <dirk.fauth@googlemail.com>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Can you please rebase and ping here? The network graph is not loading for some reason.

**Comment by fipro78** [comment]
But I rebased just before the push. Do I really need to rebase again?

**Comment by nikhilnanivadekar** [comment]
you might want to because I see Craig just merged another PR. I do not know if your PR came before Craig's. So, might want to rebase just for good measure. Sorry about the inconvenience.

**Comment by fipro78** [comment]
There is nothing new to fetch. So rebase has no effect on my side

**Comment by nikhilnanivadekar** [comment]
perfect! Merging this.

**Pull request merged**
