### PR TITLE
Upgrade maven from 3.6.1 to 3.6.3.

### PR DESCRIPTION
**Pull request by motlin**
Since we're having trouble running checkstyle through travis in #842, I figured I'd upgrade maven to the latest version to rule that out and it's a good change anyway.

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Can you move this under the other PR where you are upgrading dependencies and maven Plugins? We need to combine a few PRs to reduce the hit on Travis

**Comment by motlin** [comment]
Or we can just merge it, like you did for the EA builds. It's going to work.

**Comment by nikhilnanivadekar** [comment]
If the Travis build on your fork passed, feel free to merge it

**Comment by motlin** [comment]
This is an example where the inspections build failed for unrelated reasons. It's unfortunately flaky now.

**Comment by nikhilnanivadekar** [comment]
Can you rerun just that build and if it passes rebase and merge?

**Comment by donraab** [comment]
@motlin The build passed, so just rebase and feel free to merge. Thanks!

**Pull request merged**
