### PR TITLE
Update version numbers and add links to 10.x release notes in README.md compatibility matrix.

### PR DESCRIPTION
**Pull request by donraab**
Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
The purpose of this commit is to: Is it update version numbers or it is link to release blogs?

**Comment by nikhilnanivadekar** [comment]
I don’t think these links are going to be discoverable while reading the ReadMe. Instead I think we should update the release notes to link to the blog.

**Comment by donraab** [comment]
Why not do both (this table and release notes)? We could just limit it to 10.x in the table today. I added the links as it made more sense to add information to the 10.x versions as they were being called out individually but only showing check marks added no value.

**Comment by nikhilnanivadekar** [comment]
I would rather then update the link to direct to release notes than the blog. The reason for that is it remains static and we can update the readme during the release prep and always have an easily derivable link. It’s a pretty common workflow for developers to refer to Releases tab when they are looking for details of a specific release.

**Comment by donraab** [comment]
Ok, I will change the link to the release notes.

**Comment by nikhilnanivadekar** [comment]
Thank you! Please update the commit message as well.

**Comment by donraab** [comment]
Should be ready to merge.

**Review by nikhilnanivadekar — APPROVED** [review]

**Pull request merged**
