### PR TITLE
Move default collectors to static instances

### PR DESCRIPTION
**Pull request by Desislav-Petrov**

### CODE REVIEW

**Comment by donraab** [comment]
Hi @Desislav-Petrov, there are a couple of checkstyle failures to address. Thanks!

**Comment by Desislav-Petrov** [comment]
Oops - should be good now.

**Comment by donraab** [comment]
Hi @Desislav-Petrov I've requested a review from @motlin as I would like him to confirm the generics.

**Comment by Desislav-Petrov** [comment]
Sure, makes sense. Some of the checks seem to have been running since yesterday so was wondering if they're stuck? I dont have permissions to check though l

**Comment by donraab** [comment]
Hi @Desislav-Petrov, I re-ran the one build that was hanging. The other two builds should disappear if you rebase.

**Comment by Desislav-Petrov** [comment]
Hi @donraab - looks like one of the checks is failing but i dont think it's related to my commit

**Review by donraab — APPROVED** [review]
LGTM. Thanks for the contribution @Desislav-Petrov! The inspections 3 build is failing due to an issue unrelated to this PR so I will merge this PR and we will address the build failure separately.

**Pull request merged**
