### PR TITLE
Upgrade versions of maven plugins.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
for the enforcer plugin, please add the exception to ignore OSGi stuff.

**Comment by motlin** [comment]
@nikhilnanivadekar This fails on the tycho plugins, which I haven't touched. I've upgraded the enforcer plugin, which may have become more strict or started reporting errors which should have been reported earlier. Have you seen this before?

```
17:52:46:732 [INFO] ---------------< org.eclipse.collections:p2-repository >----------------
17:52:46:733 [INFO] Building Eclipse Collections p2 Repository Build 10.3.0-SNAPSHOT [14/15]
17:52:46:734 [INFO] --------------------------------[ pom ]---------------------------------
17:52:46:748 [INFO] 
17:52:46:749 [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce) @ p2-repository ---
17:52:46:798 [WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequirePluginVersions failed with message:
Some plugins are missing valid versions: (LATEST RELEASE SNAPSHOT are not allowed)
org.eclipse.tycho:tycho-packaging-plugin. 	The version currently in use is 1.3.0
org.eclipse.tycho:target-platform-configuration. 	The version currently in use is 1.3.0
org.eclipse.tycho:tycho-maven-plugin. 	The version currently in use is 1.3.0
```

**Comment by nikhilnanivadekar** [comment]
@motlin yeah, that's the OSGi stuff 😢 . Unfortunately, we cant do anything for it. So, for the enforcer plugin upgrade, you need to allow that dependency, however it is.

**Comment by motlin** [comment]
That seems suspicious. I'll see if I can fix it. It's probably really running with floating versions.

**Comment by motlin** [comment]
For now, I've downgraded the enforcer plugin.

**Comment by motlin** [comment]
@nikhilnanivadekar I think this and the CheckStyle builds are both failing in travis only because of https://travis-ci.community/t/disable-google-maven-central/5301

Given that we're working on moving away from travis, I don't know how much time I want to invest in this. But it seems like the workaround is just to have a settings.xml file that explicitly includes maven central.

**Comment by nikhilnanivadekar** [comment]
Do you want to add the settings.xml and try? I agree, not worth spending too much time on this.

**Comment by nikhilnanivadekar** [comment]
You might need to add the settings.xml workaround to get the builds to pass

**Comment by motlin** [comment]
I don't understand

**Comment by nikhilnanivadekar** [comment]
The Travis builds are failing. Even though we have moved majority of our builds still we will have Travis builds most likely for the Oracle JDK builds. So, I was referring to the workaround you mentioned of adding settings.xml file to get the artifacts from Maven Central.

**Comment by donraab** [comment]
@nikhilnanivadekar Do you want to have a look and merge if you are ok with all the upgrades?

**Comment by nikhilnanivadekar** [comment]
I think this should be good to merge

**Comment by donraab** [comment]
ok, i'll merge now then

**Pull request merged**
