### PR TITLE
Optimize any/all/noneSatisfy on UnifiedMapWithHashingStrategy - closes #1342

### LINKED ISSUE #1342: Optimize any/all/NoneSatisfy on UnifiedMapWithHashingStrategy
The methods `anySatisfy`, `allSatisfy` and `noneSatisfy` should be optimized on `UnifiedMapWithHashingStrategy` similar to how they are optimized on `UnifiedMap`.

### PR DESCRIPTION
**Pull request by Desislav-Petrov**
PR  - would appreciate a review @donraab 

Looks like existing tests already cover this refactoring

### CODE REVIEW

**Review by donraab — CHANGES_REQUESTED** [review]
Thank you for the contribution @Desislav-Petrov. I think it would be better to duplicate the functionality in the shortCircuit/shortCircuitWith methods than to externalize the functionality to MapIterate. MapIterate is intended to iterate over Maps, and this iterates over an array, requiring MapIterate to understand how the internals of UnifiedMap and UnifiedMapWithHashingStrategy are internally implemented.

**Comment by Desislav-Petrov** [comment]
Thanks for the review @donraab - fair points, made the changes & rebased

**Review by motlin — CHANGES_REQUESTED** [review]
To review this, I checked it out locally and diff'd UnifiedMap with UnifiedMapWithHashingStrategy. I found that the new methods were added in a different location, so diff'ing didn't work. I made the fix so that I could continue the review, but you'll have to apply it as well.

https://github.com/eclipse/eclipse-collections/commit/d4018e6e47b8d680d7a97e48267eea16dd317417

Once I did this I could see that the new implementation and the old are identical, and are good to go. Please move the methods to the same positions and then we ought to merge this.

**Comment by Desislav-Petrov** [comment]
Thx for the feedback @motlin - changes made

**Comment by motlin** [comment]
@Desislav-Petrov could you also rebase onto upstream/master and then I'll merge?

**Comment by Desislav-Petrov** [comment]
Done @motlin

**Pull request merged**
