### PR TITLE
Add toImmutableSortedListBy to Collectors2. Closes #1136

### LINKED ISSUE #1136: Add toImmutableSortedListBy to Collectors2
Add `toImmutableSortedListBy` to `Collectors2` utility class. 

See `toSortedListBy` for reference (mutable side equivalent)

### PR DESCRIPTION
**Pull request by Utkarshn10**
Signed-off-by: Utkarsh Nagar <utkarshnagar2000@gmail.com>

### CODE REVIEW

**Review by prathasirisha — APPROVED** [review]

**Comment by prathasirisha** [comment]
Hi @Utkarshn10, thank you for your contribution. Code changes look good to me. 

Can you amend the commit message to reference the issue? See point 2 [here](https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#commit-messages).  

Example commit message:  "Add toImmutableSortedListBy to Collectors2. Closes < #issue number>"

**Comment by prathasirisha** [comment]
Hi @Utkarshn10,  a minor comment - Could you please remove the word "reword" in your commit message. Also, this PR and the issue are not linked, I am guessing you have to add a space between "Closes" and "#issuesnumber".  You can see examples in the link I shared above. Thank you! :)

**Comment by Utkarshn10** [comment]
Hi @prathasirisha, thanks for helping. I have made the requested changes.

**Comment by Utkarshn10** [comment]
Hi @prathasirisha In Collections we have higher and lower but they don't work in case of equality. So what are your views on implementing these features with equality like upperbound and lowerbound  in C++ STL? Please correct me if I am wrong.

**Review by prathasirisha — APPROVED** [review]

**Comment by prathasirisha** [comment]
> Hi @prathasirisha In Collections we have higher and lower but they don't work in case of equality. What are your views on implementing these features with equality in Collections?

Hi @Utkarshn10, if you can give an example of what is not working, it will be helpful. I am going to merge this PR, so you may want to create a new issue and open it for discussion.

**Pull request merged**
