### PR TITLE
Export factory packages even from impl namespace

### PR DESCRIPTION
**Pull request by bergmanngabor**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@bergmanngabor the ip validation failed as the commit was not signed off.
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit

**Comment by nikhilnanivadekar** [comment]
Also the utility package needs to be exported as non-internal. For example: eclipse-collections/eclipse-collections/src/main/java/org/eclipse/collections/impl/utility/ListIterate.java

**Comment by bergmanngabor** [comment]
The user "noreply@github.com" needs to sign an ECA, really?

**Comment by bergmanngabor** [comment]
Sorry guys, I have only ever contributed to Eclipse via Gerrit. How do I make sure "noreply@github.com" is not recognized as a contributor?

**Comment by gs-rezaem** [comment]
@bergmanngabor your git commits in your branch are not correct. Did you use the GitHub web edit functions to edit the file? Here is what's wrong. If you do a ```git log --pretty=fuller``` in your patch-1 branch, you get:

```
commit 8ee3a64af5beda97984abee0c73b25039d2b29db
Author:     Gábor Bergmann <bergmann@mit.bme.hu>
AuthorDate: Fri Aug 18 16:33:50 2017 +0200
Commit:     GitHub <noreply@github.com>
CommitDate: Fri Aug 18 16:33:50 2017 +0200

    Export factory packages even from impl namespace
    
    Signed-Off-By: bergmann@mit.bme.hu

commit 728a3be85d54173365343aa745eb53f4258d8f95
Author:     Gábor Bergmann <bergmann@mit.bme.hu>
AuthorDate: Fri Aug 18 14:50:54 2017 +0200
Commit:     GitHub <noreply@github.com>
CommitDate: Fri Aug 18 14:50:54 2017 +0200

    Export factory packages even from impl namespace
```

Note the "Commit" field. The typical (right?) way to do this (from scratch):
clone your repo on your machine. Make sure your git settings for user name and email are correct. Apply your changes, commit, and push to github.

**Pull request closed without merging**
