### PR TITLE
Made goForward private

### PR DESCRIPTION
**Pull request by vibhuti019**
Issue #775 
goForward in IntInterval was already private.

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
Your ECA validation is not passing. Can you please follow the instructions here: https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#contributor-license
Please let me know if you need further clarification.
Thanks for your contribution.

**Comment by vibhuti019** [comment]
Please explain me the procedure.
How can I signoff my commits made through the git website

**Comment by nikhilnanivadekar** [comment]
I don’t know how to do it via git website. Generally we use git bash. Sorry!

**Comment by nikhilnanivadekar** [comment]
See #805

**Pull request closed without merging**
