### PR TITLE
Fix performance problem in MutableList.subList() and implement similar optimization as ArrayList.subList()

### PR DESCRIPTION
**Pull request by yoa1226**

### CODE REVIEW

**Comment by motlin** [comment]
This looks great, thanks. I'm wondering why additional tests are marked not applicable.

**Comment by yoa1226** [comment]
@motlin hi, motlin, Thank you for your reply. The reason why additional tests are marked not applicable is that some methods  in `MutableList`  are not implemented In it's subclass. list below :

1.  `UnmodifiableMutableList` , ` MultiReaderFastList` and ` FastListNoIterator` don't support `listIterator` and `addAll`.
2.  `CompositeFastList` don't support `addAll(int index, Collection<? extends E> c)`.

So, when unit tests about `addAll` and `listIterator` are ignored in above class.

**Review by motlin — COMMENTED** [review]
I'll share a commit with fixes to the checkstyle build as well as the ideas mentioned above.

**Comment by motlin** [comment]
Fixed in #1621

**Pull request closed without merging**
