### PR TITLE
Change math function factories to use Math.*Exact methods.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by mohrezaei** [comment]
Why do we want exceptions on overflow? It's unclear such behavior should be default when the rest of Java doesn't handle it as such, and ignoring overflow behavior is actually desired behavior in many cases (e.g. hashing, compression, cryptographic functions, etc).

**Comment by motlin** [comment]
The place where I really want this behavior is in Bags, since we use these functions to manipulate the number of occurrences. Though I suppose I could make the change just in bags to reduce impact.

**Comment by mohrezaei** [comment]
Overflow checks are of course necessary in many places, but since this is a backward breaking change, I would suggest minimizing the impact.

**Comment by motlin** [comment]
I'll close this and do it differently in Bags.

**Pull request closed without merging**
