### PR TITLE
Issue #775

### PR DESCRIPTION
**Pull request by vibhuti019**
Signed-off-by: Vibhuti Singh <vibhutisingh037@gmail.com>

### CODE REVIEW

**Comment by motlin** [comment]
The commit message should also include a description. It should be "Make org.eclipse.collections.impl.list.Interval#goForward private. Fixes #775"

**Comment by nikhilnanivadekar** [comment]
@vibhuti019 thanks for your contribution. This is ready to be merged. However, we are currently planning a minor version and this is a backwards breaking change, so, we need to wait till 11.0.0 target is opened. Once we open that (most likely in June) we will merge this. Thanks again for your help!

**Comment by nikhilnanivadekar** [comment]
@vibhuti019 the major version target is open. Can you please rebase? Also, can you please verify if the same issue exists for LongInterval and IntInterval?
Thank you!

**Comment by vibhuti019** [comment]
The issue still exits line 427 in eclipse-collections/eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java (method goForward is still public)
 
Issue resolved line 333 in eclipse-collections/eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/IntInterval.java (the method is private)

Issue resolved line 355 in eclipse-collections/eclipse-collections/src/main/java/org/eclipse/collections/impl/list/primitive/LongInterval.java (the method is private)

Can you please elaborate on what is meant by rebasing?

**Comment by nikhilnanivadekar** [comment]
@vibhuti019 you can look up rebase more here: https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase#:~:text=What%20is%20git%20rebase%3F,of%20a%20feature%20branching%20workflow.

For commands and how it works a search on your favorite search engine online will help you with the details.

**Comment by vibhuti019** [comment]
The issue still exits line 427 in eclipse-collections/eclipse-collections/src/main/java/org/eclipse/collections/impl/list/Interval.java (method goForward is still public)

@nikhilnanivadekar  should I commit and push the code again.
Or I will have create a new issue.

**Comment by nikhilnanivadekar** [comment]
Your commit is fine. Can you rebase on to upstream/master and push?
Upstream is this repo and master is this branch.

**Comment by vibhuti019** [comment]
sure sir..

**Comment by vibhuti019** [comment]
@nikhilnanivadekar  Can this be merged ?

**Comment by vibhuti019** [comment]
@nikhilnanivadekar  I will create a new issue and create a new PR

**Comment by nikhilnanivadekar** [comment]
Thanks! Merging this for Interval

**Comment by vibhuti019** [comment]
@nikhilnanivadekar  Thank You

**Pull request merged**
