### PR TITLE
maven pluginRepository: use 'https' instead of 'http'

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@sullis I am fine with this change. However, your ECA is not passing. Can you please follow the instructions here and get it signed and also sign-off your commit: 
https://github.com/eclipse/eclipse-collections/blob/master/CONTRIBUTING.md#contributor-license

**Comment by nikhilnanivadekar** [comment]
@sullis any updates on this?

**Comment by nikhilnanivadekar** [comment]
Can you please rebase on to master? I will merge it after it is rebased. Please comment back on this PR and tag me so that I can merge it immediately! Thank you for your contribution.

**Comment by sullis** [comment]
ping @nikhilnanivadekar

**Comment by nikhilnanivadekar** [comment]
Thank you @sullis

**Pull request merged**
