### PR TITLE
Remove duplicate forEach overrides.

### PR DESCRIPTION
**Pull request by donraab**
Signed-off-by: Donald Raab <Donald.Raab@bnymellon.com>

### CODE REVIEW

**Comment by donraab** [comment]
This is the definition of `forEach` in `RichIterable` which all these classes extend. 

```
    @Override
    default void forEach(Procedure<? super T> procedure)
    {
        this.each(procedure);
    }
```
I was looking at code coverage, and saw that the default method in RichIterable was not covered. Now it is.

**Comment by motlin** [comment]
I'm a fan of changes like this. I believe they are source compatible and not binary compatible. Should we wait until we know we're doing a major version?

**Comment by donraab** [comment]
Are you sure this isn't binary compatible?

https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html

"Moving a method upward in the class hierarchy."

I didn't even move the method.  It was already defined in RichIterable as a default method.

**Comment by nikhilnanivadekar** [comment]
It isn’t binary compatible because you’ll be removing implementations

**Comment by donraab** [comment]
Moving a method upward in a class hierarchy is removing a method in a subclass, no?

**Comment by motlin** [comment]
Interesting, I didn't know that's a binary compatible change.

**Pull request merged**
