### PR TITLE
adding relevant badges to website

### PR DESCRIPTION
**Pull request by bmvermeer**
Signed-off-by: bmvermeer <brianvermeer@snyk.io>
Solving issue #986

### CODE REVIEW

**Comment by bmvermeer** [comment]
@nikhilnanivadekar as requested in issue #986 
I believe these are the relevant ones to post on the website.
Cheers.

**Comment by nikhilnanivadekar** [comment]
Looks good. 1 minor nitpick, can you please amend the commit message to say "Add badges to website. Fixes #986 " please?
It will auto close the issue and commit message will be understandable in the log. Thanks a ton!

**Comment by bmvermeer** [comment]
@nikhilnanivadekar I see this is not yet merged to master. Any idea when this will happen? Thanks :)

**Comment by nikhilnanivadekar** [comment]
Oh didn’t see you pushed an amended commit.

**Comment by nikhilnanivadekar** [comment]
This looks good. Can you please rebase on to master please? And please tag me once you do it, for some reason GH notifications are not coming to me for this PR. I’ll click on merge immediately after that. Cheers!

**Comment by bmvermeer** [comment]
@nikhilnanivadekar I rebased it onto master.

**Comment by nikhilnanivadekar** [comment]
Thanks a ton @bmvermeer

**Pull request merged**
