### PR TITLE
Move maven modules 'test-coverage' and 'p2-repository' from the default list into the 'all' profile.

### PR DESCRIPTION
**Pull request by motlin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
How will this impact our release builds for normal jars and p2?

**Comment by motlin** [comment]
Good question. If the p2 builds and coverage builds don't already use the profile all or list projects using mvn command line flags, they'd have to start doing that.

**Comment by nikhilnanivadekar** [comment]
Can you update it on Jenkins and do a test milestone build?

**Comment by donraab** [comment]
@motlin Did you try a test milestone build?

**Pull request closed without merging**
