### PR TITLE
Add toImmutableSortedSetBy to Collectors2. Resolved #1137

### LINKED ISSUE #1137: Add toImmutableSortedSetBy to Collectors2
Add `toImmutableSortedSetBy` to `Collectors2` utility class. 

See `toSortedSetBy` for reference (mutable side equivalent)

### PR DESCRIPTION
**Pull request by HarrietLyBui**
Signed-off-by: Ly (Harriet) Bui <lhbui@umass.edu>

### CODE REVIEW

**Comment by donraab** [comment]
Hi @HarrietLyBui, thank you for the contribution! I approved the builds to run and there is currently a checkstyle build failure.

`
Error: 4:915 [ERROR] src/main/java/org/eclipse/collections/impl/collector/Collectors2.java:[360,6] (indentation) CommentsIndentation: Block comment has incorrect indentation level 5, expected is 4, indentation should be the same level as line 370.`

**Comment by HarrietLyBui** [comment]
> Hi @HarrietLyBui, thank you for the contribution! I approved the builds to run and there is currently a checkstyle build failure.
> 
> ` Error: 4:915 [ERROR] src/main/java/org/eclipse/collections/impl/collector/Collectors2.java:[360,6] (indentation) CommentsIndentation: Block comment has incorrect indentation level 5, expected is 4, indentation should be the same level as line 370.`

Thank you for approving the build to run. I am fixing the Checkstyle errors and will update the pull request in a sec.

**Comment by HarrietLyBui** [comment]
@donraab @Utkarshn10 @prathasirisha
I looked at the error for Findbugs checks but I am not sure how to solve it. I tried to run the test locally and got the following error

`gitpod /workspace/eclipse-collections $ mvn install findbugs:check --projects '!scala-unit-tests,!jmh-scala-tests,!jmh-tests,!jcstress-tests,!p2-repository' --activate-profiles all -DskipTests=true --no-transfer-progress
Picked up JAVA_TOOL_OPTIONS: -Xmx1879m
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/gitpod/.sdkman/candidates/maven/current
Java version: 11.0.12, vendor: Azul Systems, Inc., runtime: /home/gitpod/.sdkman/candidates/java/11.0.12.fx-zulu
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-1051-gke", arch: "amd64", family: "unix"
15:18:57:568 [INFO] Error stacktraces are turned on.
15:18:57:631 [INFO] Scanning for projects...
15:18:59:090 [ERROR] [ERROR] Could not find the selected project in the reactor: scala-unit-tests @ 
15:18:59:092 [ERROR] Could not find the selected project in the reactor: scala-unit-tests -> [Help 1]
org.apache.maven.MavenExecutionException: Could not find the selected project in the reactor: scala-unit-tests
    at org.apache.maven.graph.DefaultGraphBuilder.trimExcludedProjects (DefaultGraphBuilder.java:263)
    at org.apache.maven.graph.DefaultGraphBuilder.reactorDependencyGraph (DefaultGraphBuilder.java:125)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:84)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
15:18:59:107 [ERROR] 
15:18:59:109 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:18:59:109 [ERROR] 
15:18:59:109 [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:18:59:110 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException`

**Review by donraab — APPROVED** [review]
This looks good to me. Thanks for the contribution @HarrietLyBui !

**Comment by HarrietLyBui** [comment]
@donraab Yay! Thank you so much

**Pull request merged**
