### PR TITLE
integrating security badge on homepage.

### PR DESCRIPTION
**Pull request by bmvermeer**
This integrates the security badge on the homepage (all languages)
This will automatically update to the latest release version on maven central.

Signed-off-by: bmvermeer <brianvermeer@snyk.io>

### CODE REVIEW

**Comment by bmvermeer** [comment]
@nikhilnanivadekar again as promised. No need to update version numbers ;)

**Comment by nikhilnanivadekar** [comment]
@bmvermeer thanks for the PR. I need to merge another PR and create a service release for JDK-15, and then I will get back to this PR for a merge. Apologies for the inconvenience.

**Comment by nikhilnanivadekar** [comment]
@bmvermeer 10.4.0 is released. Can you please rebase and merge the changes?

**Comment by nikhilnanivadekar** [comment]
@bmvermeer that is because Nikhil forgot to click the merge button 😄 thanks for reminding me

**Comment by nikhilnanivadekar** [comment]
Raised #986 I cannot assign it to you unless you comment on it. Some GitHub weirdness.

**Pull request merged**
