### PR TITLE
Stop throwing mangled exceptions.

### PR DESCRIPTION
**Pull request by motlin**
If you hide spaces, this looks like a smaller change. 99 additions and 1,413 deletions.

### CODE REVIEW

**Comment by donraab** [comment]
@motlin I don't think I have a problem with this, but curious why the change is being made now, as I believe this has been like this for a very long time?

**Comment by motlin** [comment]
> @motlin I don't think I have a problem with this, but curious why the change is being made now, as I believe this has been like this for a very long time?

Do you know the history of why we have it? It has always felt unintuitive to me. It interferes subtly with tools like IntelliJ's analyze trace, and Datadog's error tracking and test tracking.

**Comment by donraab** [comment]
@motlin I can't recall why this was done.

**Comment by motlin** [comment]
> @motlin I can't recall why this was done.

From the behavior, it feels like it was designed to change stack traces of assertion failures so that the Verify class is on top. Someone probably thought that was more clear.

Usually the top of the stack trace is in your own test code, on the line that made the assertion. I think that the behavior is worse; I want to see the line in my own code.

Even if it were clearly better, it is unusual. JUnit's classes like Assert don't do it. I think it's better to test the way everyone else does.

**Review by donraab — COMMENTED** [review]
@motlin Would it be better to leave the behavior alone and just deprecate `Verify`? Eventually it needs to stop extending `Assert`, right?

**Review by donraab — APPROVED** [review]
LGTM. I have no issues with you simplifying this if it helps move it forward for the JUnit upgrade.

**Comment by motlin** [comment]
> @motlin Should we evenutally deprecate `Verify` in favor of `Assertions`? Eventually `Verify` needs to stop extending `Assert` as well, right?

`Verify` has some useful things in it, that are collection-specific assertions and failure messages. Examples:

- When comparing ordered iterables, it will show the index of the first failure
- When asserting maps are equal, it will also assert that the key and entry sets are equal

`Verify` is based on JUnit 4 primitives like `Assert` and has a lot of redundant stuff in it.

I like the idea of separate assertion libraries. JUnit 4 supports assertThat with Hamcrest matchers. Unfortunately Hamcrest is no longer maintained.

I've started to use [assertj](https://github.com/assertj/assertj) in other projects. It has [add-on modules](https://assertj.github.io/doc/) including a [Guava module](https://assertj.github.io/doc/#assertj-guava), for assertions for its Multimaps and Multisets. My ideal would be we build assertj-eclipse-collections and once stable contribute it to the upstream project.

**Pull request merged**
