### PR TITLE
Fix for #491 - if map was grown as a result of addToValue, recompute …

### PR DESCRIPTION
**Pull request by jdimeo**
…index or else it will be stale and return value will be aribitrary

Signed-off-by: John Dimeo <dimeo@elderresearch.com>

### CODE REVIEW

**Comment by gs-rezaem** [comment]
Sorry, this has a much simpler fix. Just "return value;".
:-1:

**Comment by jdimeo** [comment]
OK so what's the next step? new PR? change this PR? you guys do it instead of using PR? it's a pretty high priority fix, yes?

**Comment by nikhilnanivadekar** [comment]
Simply drop this commit and make the fix and push to the same branch. It'll update the PR and we will remove.

**Comment by jdimeo** [comment]
Will do that hopefully tonight.

**Comment by gs-rezaem** [comment]
Please add a test case as well and fix any checkstyle issues (if any).

**Comment by jdimeo** [comment]
@gs-rezaem I'm having a hard time locating in which submodule and which test the right place to add the test would be...

**Comment by nikhilnanivadekar** [comment]
@jdimeo please push what you have with the fix, I can cherry-pick the commit and help out from there. Similar to what I did here: https://github.com/nikhilnanivadekar/eclipse-collections/commit/6f9ea99f701d380127e87c3d3ab3f1c3b584cfd7

**Comment by jdimeo** [comment]
Well, I finally found where to add the test, but when I converted the `long` test values to `int`s to conform to how the existing `addToValue` test was set up, it no longer demonstrated the bug.

I've attached a patch with how far I got adding the test (which unfortunately passes before the fix was implemented, so the correct values will have to be found).
[patch.diff.txt](https://github.com/eclipse/eclipse-collections/files/1854286/patch.diff.txt)

**Comment by jdimeo** [comment]
Oh dear, now I seem to have broken the build but I'm not sure how. All unit tests passed but the exception was thrown at the end of the acceptance test suite:
`Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?`

**Comment by nikhilnanivadekar** [comment]
@jdimeo that is fine. It happens for acceptance suite since it is a long running build. I have re-triggered it.
I am checking the test cases.

**Comment by nikhilnanivadekar** [comment]
In the test case, you need to pre-size the map so that insert in Map will trigger a rehash.
Here are failing tests:

```
@Test
public void addToValue()
{
    ObjectIntHashMap<String> emptyMap = this.getEmptyMap();
    IntInterval interval = IntInterval.zeroTo(10);
    interval.forEachWithIndex(new IntIntProcedure() {
        @Override
        public void value(int each, int index)
        {
            Assert.assertEquals("Key:" + each, each + index, emptyMap.addToValue(String.valueOf(each), each + index));
        }
    });
}
```
```
@Test
public void addToValue()
{
    MutableLongLongMap emptyMap = this.getEmptyMap();
    MutableLongList longList = LongLists.mutable.with(936628237L, 4889384619L, 8733915902L, 2377747912L,
            277382636L, 593670575L, 296725141L, 7131901003L, 9986389012L);
    longList.forEachWithIndex((each, index) ->
            Assert.assertEquals("Key:" + each, each + index, emptyMap.addToValue(each, each + index)));
}
```

**Comment by nikhilnanivadekar** [comment]
@jdimeo was this helpful?

**Comment by jdimeo** [comment]
@nikhilnanivadekar Yes, I think so. Sorry, I've been really slammed this week and haven't had a chance to revisit this. Are you waiting for me to add a test to this PR? I will do that at my next opportunity.

**Comment by nikhilnanivadekar** [comment]
I understand. I am will wait to merge, so that I can back port it and create service releases.
Thanks for your help!

**Comment by jdimeo** [comment]
OK, I added tests to the unit test templates that I confirmed failed prior to my fix and pass after it. 
@nikhilnanivadekar on 3. above, doesn't it not apply to PrimitiveObjectHashMap since that class doesn't have `addToValue`?

**Comment by jdimeo** [comment]
I think I have done that now. I saw a button to do it when I first requested the merge, but now I had to do it with git commands and then force push. Please let me know if I didn't do it correctly.

**Comment by nikhilnanivadekar** [comment]
@jdimeo Thanks for your contribution!

**Pull request merged**
