### PR TITLE
Correct typos in syntax diagram callouts in EC Reference Guide

### PR DESCRIPTION
**Pull request by proverbialSol**
Updated png file for syntax diagram, correcting typos, plus a light edit for clarity; also added a Markdown doc of the callout text.

### CODE REVIEW

**Comment by proverbialSol** [comment]
Unclear to me what has failed here... Should I have raised an issue before creating this request?

**Comment by nikhilnanivadekar** [comment]
A few things are going on here. The IP validation passes but there are multiple commits for this PR, we need them to be squashed to be one. One of the commits is to bring it insync with the head. 
To fix this, it requires a bit of git trickery, and if you are not comfortable I can pick your commits and help you out. If you would like to learn some cool git tricks, happy to help you with that as well. Please let me know, what you would like. Cheers!

**Comment by proverbialSol** [comment]
Yes, please... show me how. 

First off, I'm not sure how this came to be three separate commits... I recall that I may have accidentally repeated some action (like uploading the two files). But why 3 commits? 

Also unaware that that commits could be merged. (I understood "merge" as what a PR essentially requests).

Appreciate the handholding here... best/r

**Comment by nikhilnanivadekar** [comment]
closing due to inactivity.

**Pull request closed without merging**
