### PR TITLE
Add an instruction to write a draft release note to CONTRIBUTING.md.

### PR DESCRIPTION
**Pull request by itohro**
(Ignore  d3d00c9 which is part of PR #71 )

- Added RELEASE_NOTE_DRAFT.md that includes changes for 7.1.0 committed so far.
- Added an instruction to write a draft release note to CONTRIBUTING.md.

### CODE REVIEW

**Comment by motlin** [comment]
Added suggested edits in my fork. Let me know what you think.

**Comment by motlin** [comment]
This one needs to be rebased now and conflicts resolved.

**Comment by itohro** [comment]
Rebased.

**Comment by motlin** [comment]
Made more edits which you can see here https://github.com/eclipse/eclipse-collections/compare/master...motlin:release-note-draft

**Comment by itohro** [comment]
Thanks! The changes look good to me.

**Comment by itohro** [comment]
Sounds good and done.

**Pull request merged**
