### PR TITLE
fix JDK 16 illegal access

### LINKED ISSUE #1075: FastList broken after upgrade to java 16 from 15 due to module error
Hi I just upgraded to java 16 in eclipse and now fastutil is throwing an error 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.eclipse.collections.impl.list.mutable.FastList.addAllArrayList(FastList.java:311)
	at org.eclipse.collections.impl.list.mutable.FastList.addAll(FastList.java:283)
	at main.Start.main(Start.java:20)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.lang.Object[] java.util.ArrayList.elementData accessible: module java.base does not "opens java.util" to unnamed module @66ff6b1
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.eclipse.collections.impl.utility.ArrayListIterate.<clinit>(ArrayListIterate.java:108)
	... 4 more

worked fine in java 15, all I am doing is creating a new fastlist<String> and populating it using a List<String> to addAll()

I can get round the problem using the VM flag
--add-opens java.base/java.util=ALL-UNNAMED
but this is only a workaround not a bugfix.

### PR DESCRIPTION
**Pull request by mohrezaei**
Fixes #1075 
Also testing no "signed-off-by"

### CODE REVIEW

**Comment by mohrezaei** [comment]
Should also be backported as far back as reasonable.

**Review by nikhilnanivadekar — APPROVED** [review]

**Comment by mohrezaei** [comment]
For the backport, 10.4.1 seems like a better number. This should easily be binary compatible.

**Comment by nikhilnanivadekar** [comment]
@mohrezaei if I may request, can you add an addAll() with ArrayList in AbstractRichIterableTest to ensure this is really fixed?

**Comment by mohrezaei** [comment]
I'm trying to understand why this wasn't throwing in our JDK 16 build. Do we need a newer JDK 16 or something?

**Comment by donraab** [comment]
Agree with @mohrezaei I would have expected our JDK 16 build to fail. Here's a test in FastListTest.

```
    @Test
    public void addAllWithMultipleTypes()
    {
        FastList<Integer> list = FastList.newList();
        list.addAll(mList(1, 2, 3, 4));
        list.addAll(mSet(5, 6));
        list.addAll(new ArrayList<>(mList(7, 8)));
        list.addAll(this.newWith(9, 10));
        Assert.assertFalse(list.addAll(Lists.mutable.of()));
        Assert.assertEquals(this.newWith(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), list);
    }
```

**Comment by nikhilnanivadekar** [comment]
We download the latest JDK build and then run it. Can you test in your local if the test fails? I wonder if it is a test issue or a build issue?

**Pull request closed without merging**
