### PR TITLE
Add missing Override annotations

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by nikhilnanivadekar** [comment]
@Godin Thanks for the PR. 
Can you please make similar changes in other stg files? I have listed 15 below. All the files are in one module, and seems to me that all the stg files need the Override annotations

1. mutablePrimitiveCollection.stg
2. immutablePrimitiveCollection.stg
3. abstractMutablePrimitiveKeySet.stg
4. abstractMutablePrimitiveValuesMap.stg
5. objectPrimitiveHashMapWithHashingStrategy.stg
6. objectPrimitiveHashMap.stg
7. synchronizedPrimitiveObjectMap.stg
8. immutablePrimitiveObjectEmptyMap.stg
9. immutablePrimitiveObjectHashMap.stg
10. immutablePrimitiveObjectSingletonMap.stg
11. immutablePrimitiveArrayList.stg
12. immutablePrimitiveEmptyList.stg
13. immutablePrimitiveBagFactoryImpl.stg
14. immutablePrimitiveHashBag.stg
15. immutablePrimitiveEmptyBag.stg

**Comment by Godin** [comment]
Hey, where is fair play? Other way around would already gave me 16 contributions :wink: :laughing:

And more honestly - I've already got tired after fixing 200+ in `primitiveObjectHashMap.stg`. Maybe I miss some magical tooling that you guys have for applying such refactorings on `stg` files. But okay, give me some time to warm my keyboard by fixing another thousand.

**Comment by nikhilnanivadekar** [comment]
@godin :) no magic tooling. I already have fixed many from that list. 
TBH I would rather have you take a look at Java 9 support. 
I can cherry pick this commit and finish this, if you want to look at Java 9 support.

**Comment by Godin** [comment]
@nikhilnanivadekar should be far better now. Hope there are no leftovers, but even if there are highly advise to deal with them separately - they will be uncovered almost immediately after merge of this.

**Comment by nikhilnanivadekar** [comment]
@Godin on a different note, I have raised issues and assigned them to me for other fixes pointed by Sonar. I will fix them, want to make sure both of us don't end up doing the same work :-)

**Pull request merged**
