### PR TITLE
stop using deprecated compile dependency declaration

### PR DESCRIPTION
**Pull request by LarsEckart**
Signed-off-by: Lars Eckart <lars.eckart@gmail.com>

hello, my first contribution, I hope i got the eclipse account and contributer agreement done correctly :)

### CODE REVIEW

**Comment by LarsEckart** [comment]
unit test check failed.
12:05:46:394 [ERROR] Errors: 
12:05:46:394 [ERROR]   Collectors2AdditionalTest.sumByFloatParallel:200 » ArrayIndexOutOfBounds

since I only changed the README, I guess we discovered a flaky test?

**Comment by LarsEckart** [comment]
To me it looks like there is not much I can do about that failed test, given my changes. Do you have any recommendations or insights about the failure?

**Comment by nikhilnanivadekar** [comment]
I have retriggered the job. Let’s see if it succeeds this time. You’ll need to rebase on to master as well.

**Comment by nikhilnanivadekar** [comment]
thank you for your contribution.

**Pull request merged**
